apache/incubator-skywalking-ui

- .travis.yml
- pom.xml
- travis/push_image.sh
Add the following variables and the corresponding values into Environment Variables of corresponding project in Travis CI
```
DOCKER_PASSWORD: the password of docker user 
DOCKER_USERNAME: username of docker
```
> Push docker image when sky-walking-ui is tagged

- pom.xml
- src/main/java/org/skywalking/apm/ui/controller/TopTraceListController.java
- src/main/java/org/skywalking/apm/ui/service/TopTraceListService.java
- src/main/resources/static/trace/top-trace-list.js
- src/main/resources/static/trace/trace.html
- src/main/resources/static/trace/trace.js
> Fixed #218, add operation name to be a query condition in trace page.

- src/main/java/org/skywalking/apm/ui/controller/HealthController.java
- src/main/java/org/skywalking/apm/ui/service/HealthService.java
- src/main/resources/static/health/applications.html
- src/main/resources/static/health/applications.js
- src/main/resources/static/health/health.html
> instance health test success.

- src/main/resources/public/js/gc-chart.js
- src/main/resources/public/js/memory-chart.js
- src/main/resources/public/js/metric-chart.js
- src/main/resources/static/instance/instance.js
- src/main/resources/static/instance/metricCharts.js
- src/main/resources/static/main.js
> fix jvm metric issue

- src/main/resources/log4j2.xml
- src/main/resources/static/health/health.js
- src/main/resources/static/service/serviceTree.html
- src/main/resources/static/service/serviceTree.js
- src/main/resources/static/timeAxis/timeAxis.html
- src/main/resources/static/timeAxis/timeAxis.js
https://github.com/wu-sheng/sky-walking/issues/435
> provide change time with calendar

- src/main/java/org/skywalking/apm/ui/controller/TopTraceListController.java
- src/main/java/org/skywalking/apm/ui/service/TopTraceListService.java
- src/main/resources/static/trace/span.html
- src/main/resources/static/trace/top-trace-list.html
- src/main/resources/static/trace/top-trace-list.js
- src/main/resources/static/trace/trace.html
- src/main/resources/static/trace/trace.js
https://github.com/wu-sheng/sky-walking/issues/401
> Provide error and application query condition in trace stack UI.

- pom.xml
404    /webjars/momentjs/2.18.1/min/moment.min.js
> momentjs in pom.xml

- public/font/iconfont/iconfont.svg
these icon files are under MIT license:
refrence:https://github.com/ant-design/ant-design/issues/10243#event-1593439370
> Icons Add License

- DISCLAIMER
Based on last vote comments by IPMC
> Adjust declaimer.

- mock/service.js
- mock/trace.js
- src/components/Trace/TraceList/index.js
- src/models/service.js
- src/models/trace.js
- src/routes/Service/Service.js
For https://github.com/apache/incubator-skywalking/issues/1393
> 5.0.0/beta2

- src/components/Authorized/PromiseRender.js
- src/components/Charts/Area/index.js
- src/components/Charts/Bar/index.js
- src/components/Charts/ChartCard/index.js
- src/components/Charts/HeatMap/index.js
- src/components/Charts/Line/index.js
- src/components/Charts/Pie/index.js
- src/components/Charts/StackBar/index.js
- src/components/Duration/Icon/index.js
- src/components/Duration/Panel/currentTimePanel.js
- src/components/Duration/Panel/index.js
- src/components/Login/LoginItem.js
- src/components/Login/LoginTab.js
- src/components/Login/index.js
- src/components/NoticeIcon/index.js
- src/components/Page/Panel/index.js
- src/components/Page/Search/index.js
- src/components/SiderMenu/SiderMenu.js
- src/components/Topology/AppTopology.js
- src/components/TraceStack/index.js
- src/layouts/BasicLayout.js
- src/routes/Alarm/Alarm.js
- src/routes/Endpoint/Endpoint.js
- src/routes/Service/Service.js
- src/routes/Topology/Topology.js
- src/routes/Trace/Trace.js
- src/routes/Trace/TraceSearch.js
- src/routes/User/Login.js
- src/routes/User/Register.js
> Update: fix the CI issues

- src/components/TraceStack/index.js
- src/components/TraceStack/index.less
1. update colorsList(6 items) into d3.scaleSequential(mutiple items) support more services.
2. update the span's style.
2. update the span's content out of the board bug.
> Update: TraceStack

- .webpackrc.js
- src/components/TraceTree/d3-trace.js
- src/components/TraceTree/index.js
- src/components/TraceTree/style.less
1.Add top childrens and top slow span.
2.fix windowresize bug.
3.fix time and span tiptip connection.
4.Optimized tree rendering algorithm.
> Feature: update spans display

- .webpackrc.js
> Revert address to localhost

- src/routes/Topology/Topology.js
topology page data are
```json
{
"data": {
"getGlobalTopology": {
"nodes": [
{
"id": "1",
"name": "User",
"type": "USER",
"isReal": false
},
{
"id": "2",
"name": "projectB",
"type": "SpringMVC",
"isReal": true
},
{
"id": "3",
"name": "projectC",
"type": "SpringMVC",
"isReal": true
},
{
"id": "4",
"name": "projectA",
"type": "SpringMVC",
"isReal": true
},
{
"id": "5",
"name": "projectD",
"type": "kafka-consumer",
"isReal": true
},
{
"id": "6",
"name": "localhost:8761",
"type": "Unknown",
"isReal": false
},
{
"id": "9",
"name": "www.baidu.com:80",
"type": "Unknown",
"isReal": false
},
{
"id": "10",
"name": "127.0.0.1:9092",
"type": "Kafka",
"isReal": false
}
],
"calls": [
{
"id": "2_6_2",
"source": "2",
"target": "6",
"callType": "HttpClient",
"detectPoint": "CLIENT"
},
{
"id": "3_10_40", …
```
> fix topology page "Filter application"  no items

- src/components/TraceStack/index.js
Optimization: change treeMode hide card maybe the user experience will be better.
change treeMode can not close the detail card in open.
> Optimization: change treeMode

- src/components/TraceTree/d3-trace.js
Issue Url: https://github.com/apache/incubator-skywalking/issues/2200
Local span layer and layer text is Unknown  => 'Local'
Snapshot like this:
> Optimization: Local span layer issue

- .roadhogrc.mock.js
- mock/database.js
- src/common/menu.js
- src/common/router.js
- src/components/Database/DatabaseChartArea/index.js
- src/components/Database/DatabaseChartBar/index.js
- src/components/Database/DatabaseChartLine/index.js
- src/components/Database/index.js
- src/models/database.js
- src/routes/Database/Database.js
- src/routes/Endpoint/Endpoint.js
- src/routes/Service/Service.js
1. update the database page.
2. update the database mock.
3. update the database router.
4. update the database query.
5. update the service and databse select width.
> Update: update database feature.

- .roadhogrc.mock.js
- src/components/Trace/TraceListDB/index.js
- src/components/Trace/TraceListDB/index.less
- src/models/database.js
- src/routes/Database/Database.js
> Feature: add database traceList

- src/components/Charts/ChartCard/index.less
fix monitor service page layout issue #229
> fix monitor service page layout issue

- src/components/Trace/TraceListDB/index.js
> Update: update db-trace copy

- .roadhogrc.mock.js
- mock/trace.js
- src/models/trace.js
- src/routes/Trace/TraceSearch.js
1. Fix mock
2. Add serviceInstance Search Support
> Feature: Add serviceInstance Search Support

- src/routes/Topology/Topology.js
Fix Errors in filling out rules
> Fix: fix bug #2276
